import type { Metadata } from "next";
import { PageHero } from "@/components/PageHero";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy",
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <PageHero title="Privacy Policy" />
      <section className="bg-white">
        <div className="site-container max-w-3xl space-y-6 section-y text-base leading-8 text-td-muted">
          <p>
            {site.name} (“we,” “us”) operates this website. This page describes how
            information submitted through the site is used.
          </p>
          <p>
            If you use the consultation form, we collect the name, email address,
            telephone number, practice area, and message you provide so we can
            respond to your inquiry. We may also receive technical information
            automatically generated by your browser, such as IP address and pages
            visited, as part of ordinary website operation.
          </p>
          <p>
            We use that information to evaluate and respond to requests for legal
            services and to operate the website. We do not sell personal
            information. Submitting the form does not, by itself, create an
            attorney-client relationship.
          </p>
          <p>
            Questions about this policy may be sent to{" "}
            <a href={site.emailHref}>{site.email}</a> or by calling{" "}
            <a href={site.phoneHref}>{site.phone}</a>. Our office is located at{" "}
            {site.address.line1}, {site.address.line2}.
          </p>
        </div>
      </section>
    </>
  );
}
